# -*- coding: utf-8 -*-
"""NFHS5_Health_Analysis (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnDizRg-1Mi4gKUoFI7GJZEuYI9PJ3Wn
"""

!pip install folium --quiet
print('All packages ready.')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import folium
import requests
import warnings
warnings.filterwarnings('ignore')
plt.rcParams.update({'figure.dpi':130,'axes.titlesize':14,
                     'axes.labelsize':12,'xtick.labelsize':10,'ytick.labelsize':10})
print('Libraries imported.')

from google.colab import files
uploaded = files.upload()
CSV_PATH = list(uploaded.keys())[0]
print(f'Uploaded: {CSV_PATH}')

raw = pd.read_csv(CSV_PATH)
print('Raw shape:', raw.shape)
print('Columns:', raw.columns.tolist())
raw.head(5)

# Pivot: rows = states, columns = indicator text, values = nfhs5_total
wide = raw.pivot_table(index='state', columns='indicator',
                       values='nfhs5_total', aggfunc='first')


INDICATOR_MAP = {
    'Obesity_Women':        '88. Women who are overweight or obese',
    'Obesity_Men':          '89. Men who are overweight or obese',
    'Anaemia_Children':     '92. Children age 6-59 months who are anaemic',
    'Anaemia_Women':        '95. All women age 15-49 years who are anaemic',
    'HighBloodSugar_Women': '101. Blood sugar level - high or very high',
    'HighBloodSugar_Men':   '104. Blood sugar level - high or very high',
    'Hypertension_Women':   '107. Elevated blood pressure',
    'Hypertension_Men':     '110. Elevated blood pressure',
}

def find_col(wide_df, substring):
    matches = [c for c in wide_df.columns if substring in c]
    if not matches:
        raise KeyError(
            f"No column found containing: '{substring}'\n"
            f"Available cols sample: {list(wide_df.columns[:5])}"
        )
    return matches[0]

df = pd.DataFrame(index=wide.index)
for friendly, substr in INDICATOR_MAP.items():
    col = find_col(wide, substr)
    df[friendly] = pd.to_numeric(wide[col], errors='coerce')
    print(f"  {friendly:25s} <- '{col[:65]}'")

df = df[df.index != 'India'].copy()
print(f"\nClean DataFrame shape: {df.shape}")
print("\nMissing values per column:")
print(df.isnull().sum())
df.head()

df['Gender_Obesity_Gap'] = df['Obesity_Women'] - df['Obesity_Men']
print("Top 10 states by Gender Obesity Gap (Women minus Men):")
print(df['Gender_Obesity_Gap'].sort_values(ascending=False).head(10).to_string())
df[['Obesity_Women','Obesity_Men','Gender_Obesity_Gap']].sort_values('Gender_Obesity_Gap', ascending=False).head(10)

corr_cols = ['Obesity_Women','Obesity_Men',
             'Anaemia_Children','Anaemia_Women',
             'HighBloodSugar_Women','HighBloodSugar_Men',
             'Hypertension_Women','Hypertension_Men']

corr_matrix = df[corr_cols].corr(method='pearson')

fig, ax = plt.subplots(figsize=(10, 8))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt=".2f",
            cmap='RdYlGn', center=0, vmin=-1, vmax=1,
            linewidths=0.5, ax=ax, cbar_kws={'label': 'Pearson r'})
ax.set_title("Pearson Correlation Matrix - NFHS-5 Health Indicators\n(State-level, n=36)",
             fontsize=14, fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig('correlation_matrix.png', bbox_inches='tight')
plt.show()

r = corr_matrix.loc['Anaemia_Children','Obesity_Women']
print(f"Pearson r (Child Anaemia vs Women Obesity) = {r:.3f}")
if r < -0.3:
    print("  -> Negative correlation: supports the double-burden hypothesis.")
elif r > 0.3:
    print("  -> Positive correlation: anaemia and obesity co-occur in the same states.")
else:
    print("  -> Weak correlation: no strong linear relationship across states.")

top10_hyp = (
    df[['Hypertension_Men','Hypertension_Women']]
    .dropna()
    .assign(avg=lambda x: x.mean(axis=1))
    .nlargest(10,'avg')
    .drop(columns='avg')
    .sort_values('Hypertension_Men', ascending=False)
)

x = np.arange(len(top10_hyp))
width = 0.38
fig, ax = plt.subplots(figsize=(13, 6))
bars_m = ax.bar(x - width/2, top10_hyp['Hypertension_Men'],
                width, label='Men', color='#2196F3', edgecolor='white', linewidth=0.8)
bars_w = ax.bar(x + width/2, top10_hyp['Hypertension_Women'],
                width, label='Women', color='#E91E63', edgecolor='white', linewidth=0.8)
ax.bar_label(bars_m, fmt='%.1f%%', padding=3, fontsize=9, color='#1565C0')
ax.bar_label(bars_w, fmt='%.1f%%', padding=3, fontsize=9, color='#880E4F')
ax.set_xticks(x)
ax.set_xticklabels(top10_hyp.index, rotation=30, ha='right')
ax.set_ylabel('Population with Elevated Blood Pressure (%)')
ax.set_xlabel('State / UT')
ax.set_title('Top 10 States by Hypertension - NFHS-5\n(Elevated BP or on medication)',
             fontweight='bold')
ax.legend(title='Gender', framealpha=0.9)
ax.set_ylim(0, top10_hyp.max().max() * 1.18)
ax.yaxis.grid(True, linestyle='--', alpha=0.5)
ax.set_axisbelow(True)
plt.tight_layout()
plt.savefig('hypertension_bar_chart.png', bbox_inches='tight')
plt.show()
print("Bar chart saved.")

STATE_ABBR = {
    'Andaman & Nicobar Islands':'AN','Andhra Pradesh':'AP','Arunachal Pradesh':'AR',
    'Assam':'AS','Bihar':'BR','Chandigarh':'CH','Chhattisgarh':'CG',
    'Dadra & Nagar Haveli and Daman & Diu':'DNDD','NCT Delhi':'DL','Goa':'GA',
    'Gujarat':'GJ','Himachal Pradesh':'HP','Haryana':'HR','Jharkhand':'JH',
    'Jammu & Kashmir':'JK','Karnataka':'KA','Kerala':'KL','Lakshadweep':'LD',
    'Ladakh':'LA','Maharashtra':'MH','Meghalaya':'ML','Manipur':'MN',
    'Madhya Pradesh':'MP','Mizoram':'MZ','Nagaland':'NL','Odisha':'OD',
    'Punjab':'PB','Puducherry':'PY','Rajasthan':'RJ','Sikkim':'SK',
    'Telangana':'TG','Tamil Nadu':'TN','Tripura':'TR','Uttar Pradesh':'UP',
    'Uttarakhand':'UK','West Bengal':'WB',
}
REGION = {
    'AR':'NE','AS':'NE','MN':'NE','ML':'NE','MZ':'NE','NL':'NE','SK':'NE','TR':'NE',
    'KL':'South','TN':'South','AP':'South','TG':'South','KA':'South','GA':'South','PY':'South',
    'MH':'West','GJ':'West','RJ':'West',
    'UP':'North','HR':'North','PB':'North','HP':'North','UK':'North',
    'DL':'North','JK':'North','CH':'North','LA':'North',
    'MP':'Central','CG':'Central','JH':'Central','OD':'Central','WB':'Central','BR':'Central',
    'AN':'Island','LD':'Island','DNDD':'Island',
}
REGION_COLOR = {
    'NE':'#9C27B0','South':'#F44336','West':'#FF9800',
    'North':'#2196F3','Central':'#4CAF50','Island':'#795548'
}

sdf = df[['Anaemia_Women','Obesity_Women']].dropna().copy()
sdf['abbr']   = sdf.index.map(STATE_ABBR)
sdf['region'] = sdf['abbr'].map(REGION).fillna('Other')

fig, ax = plt.subplots(figsize=(13, 8))
for region, grp in sdf.groupby('region'):
    ax.scatter(grp['Anaemia_Women'], grp['Obesity_Women'],
               color=REGION_COLOR.get(region,'#607D8B'),
               s=90, edgecolors='white', linewidths=0.7, label=region, zorder=3)
for _, row in sdf.iterrows():
    ax.annotate(row['abbr'], xy=(row['Anaemia_Women'], row['Obesity_Women']),
                xytext=(4,4), textcoords='offset points', fontsize=7.5, color='#333333')

x_v, y_v = sdf['Anaemia_Women'], sdf['Obesity_Women']
m_coef, b_coef = np.polyfit(x_v, y_v, 1)
xline = np.linspace(x_v.min(), x_v.max(), 100)
r_val = np.corrcoef(x_v, y_v)[0,1]
ax.plot(xline, m_coef*xline + b_coef, '--', color='gray',
        linewidth=1.5, alpha=0.7, label=f'Trend (r={r_val:.2f})')

ax.set_xlabel('Anaemic Women Age 15-49 (%)')
ax.set_ylabel('Overweight/Obese Women - BMI >= 25 (%)')
ax.set_title('Anaemia vs Obesity Among Women - NFHS-5 (State-level)\nColour = Geographic Region',
             fontweight='bold')
ax.legend(title='Region', bbox_to_anchor=(1.01,1), loc='upper left', framealpha=0.9)
ax.yaxis.grid(True, linestyle='--', alpha=0.4)
ax.set_axisbelow(True)
plt.tight_layout()
plt.savefig('scatter_anaemia_vs_obesity.png', bbox_inches='tight')
plt.show()
print("Scatter plot saved.")

CAPITALS = {
    'Andaman & Nicobar Islands': (11.6234, 92.7265),
    'Andhra Pradesh':            (15.9129, 79.7400),
    'Arunachal Pradesh':         (27.0844, 93.6053),
    'Assam':                     (26.1445, 91.7362),
    'Bihar':                     (25.5941, 85.1376),
    'Chandigarh':                (30.7333, 76.7794),
    'Chhattisgarh':              (21.2514, 81.6296),
    'Dadra & Nagar Haveli and Daman & Diu': (20.1809, 73.0169),
    'NCT Delhi':                 (28.7041, 77.1025),
    'Goa':                       (15.4909, 73.8278),
    'Gujarat':                   (23.2156, 72.6369),
    'Himachal Pradesh':          (31.1048, 77.1734),
    'Haryana':                   (29.0588, 76.0856),
    'Jharkhand':                 (23.6102, 85.2799),
    'Jammu & Kashmir':           (34.0836, 74.7973),
    'Karnataka':                 (12.9716, 77.5946),
    'Kerala':                    ( 8.5241, 76.9366),
    'Lakshadweep':               (10.5667, 72.6417),
    'Ladakh':                    (34.1526, 77.5771),
    'Maharashtra':               (19.0760, 72.8777),
    'Meghalaya':                 (25.5788, 91.8933),
    'Manipur':                   (24.8170, 93.9368),
    'Madhya Pradesh':            (23.2599, 77.4126),
    'Mizoram':                   (23.7307, 92.7173),
    'Nagaland':                  (25.6751, 94.1086),
    'Odisha':                    (20.2961, 85.8245),
    'Punjab':                    (30.7333, 76.7794),
    'Puducherry':                (11.9416, 79.8083),
    'Rajasthan':                 (26.9124, 75.7873),
    'Sikkim':                    (27.3314, 88.6138),
    'Telangana':                 (17.3850, 78.4867),
    'Tamil Nadu':                (13.0827, 80.2707),
    'Tripura':                   (23.8315, 91.2868),
    'Uttar Pradesh':             (26.8467, 80.9462),
    'Uttarakhand':               (30.0668, 79.0193),
    'West Bengal':               (22.5726, 88.3639),
}
print(f"Capitals defined for {len(CAPITALS)} states/UTs")

GEOJSON_URL = (
    "https://raw.githubusercontent.com/geohacker/india/master/state/india_telengana.geojson"
)
geo_resp = requests.get(GEOJSON_URL, timeout=30)
if geo_resp.status_code == 200:
    india_geo = geo_resp.json()
    print(f"GeoJSON loaded | Features: {len(india_geo['features'])}")
    print("Sample properties:", list(india_geo['features'][0]['properties'].keys()))
else:
    raise RuntimeError(f"GeoJSON download failed: {geo_resp.status_code}")

GEO_NAME_KEY = 'NAME_1'
NAME_FIX = {
    'Andaman and Nicobar':    'Andaman & Nicobar Islands',
    'Arunanchal Pradesh':     'Arunachal Pradesh',
    'Jammu and Kashmir':      'Jammu & Kashmir',
    'Dadra and Nagar Haveli': 'Dadra & Nagar Haveli and Daman & Diu',
    'Daman and Diu':          'Dadra & Nagar Haveli and Daman & Diu',
    'Delhi':                  'NCT Delhi',
    'Pondicherry':            'Puducherry',
    'Uttaranchal':            'Uttarakhand',
    'Orissa':                 'Odisha',
}
for feat in india_geo['features']:
    raw_name = feat['properties'].get(GEO_NAME_KEY, '')
    feat['properties']['state_name'] = NAME_FIX.get(raw_name, raw_name)
print("GeoJSON state names normalised.")
print("Sample:", [f['properties']['state_name'] for f in india_geo['features'][:5]])

# Prepare choropleth data
choro_df = df[['Obesity_Women','HighBloodSugar_Women','Anaemia_Children']].copy()
choro_df.index.name = 'state'
choro_df = choro_df.reset_index().rename(columns={'state':'state_name'})

# Initialise Folium map of India
m = folium.Map(location=[20.5937, 78.9629], zoom_start=5, tiles='CartoDB positron')

# Choropleth shaded by Women Obesity
folium.Choropleth(
    geo_data=india_geo,
    name='Women Obesity (%)',
    data=choro_df,
    columns=['state_name','Obesity_Women'],
    key_on='feature.properties.state_name',
    fill_color='YlOrRd',
    fill_opacity=0.75,
    line_opacity=0.4,
    nan_fill_color='#cccccc',
    legend_name='Women Overweight/Obese - BMI >= 25 (%)',
    highlight=True,
).add_to(m)

# CircleMarker layer for each state capital
marker_group = folium.FeatureGroup(name='State Health Indicators', show=True)

for state, (lat, lon) in CAPITALS.items():
    row = df.loc[df.index == state]
    if row.empty:
        continue
    obs   = row.iloc[0]
    bsg   = obs.get('HighBloodSugar_Women', float('nan'))
    anaem = obs.get('Anaemia_Children',     float('nan'))
    obes  = obs.get('Obesity_Women',        float('nan'))

    if   np.isnan(obes): c_col = '#aaaaaa'
    elif obes >= 30:     c_col = '#d32f2f'
    elif obes >= 20:     c_col = '#f57c00'
    elif obes >= 10:     c_col = '#fbc02d'
    else:                c_col = '#388e3c'

    bsg_str  = f"{bsg:.1f}%" if not np.isnan(bsg)   else "N/A"
    anm_str  = f"{anaem:.1f}%" if not np.isnan(anaem) else "N/A"
    obs_str  = f"{obes:.1f}%" if not np.isnan(obes)  else "N/A"

    tip = (
        "<div style='font-family:Arial;font-size:12px;width:230px;"
        "background:#fff;padding:8px;border-radius:6px;"
        "box-shadow:1px 1px 4px rgba(0,0,0,0.3);'>"
        f"<b style='font-size:13px;'>{state}</b>"
        "<hr style='margin:4px 0'>"
        f"High Blood Sugar (Women): <b>{bsg_str}</b><br>"
        f"Child Anaemia (6-59 m): <b>{anm_str}</b><br>"
        f"Women Obesity (BMI>=25): <b>{obs_str}</b>"
        "</div>"
    )

    folium.CircleMarker(
        location=[lat, lon], radius=7,
        color='white', weight=1.5,
        fill=True, fill_color=c_col, fill_opacity=0.9,
        tooltip=folium.Tooltip(tip, sticky=True),
    ).add_to(marker_group)

marker_group.add_to(m)
folium.LayerControl(collapsed=False).add_to(m)

legend_html = (
    "<div style='position:fixed;bottom:40px;left:40px;z-index:1000;"
    "background:white;padding:10px 14px;border-radius:8px;"
    "border:1px solid #ccc;font-family:Arial;font-size:12px;'>"
    "<b>Circle: Women Obesity Level</b><br>"
    "<span style='color:#d32f2f;'>&#9679;</span> >= 30% (High)<br>"
    "<span style='color:#f57c00;'>&#9679;</span> 20-30% (Moderate)<br>"
    "<span style='color:#fbc02d;'>&#9679;</span> 10-20% (Low)<br>"
    "<span style='color:#388e3c;'>&#9679;</span> < 10% (Very Low)<br>"
    "<span style='color:#aaaaaa;'>&#9679;</span> No data"
    "</div>"
)
m.get_root().html.add_child(folium.Element(legend_html))

print("Folium map built successfully.")
m

map_path = 'nfhs5_india_health_map.html'
m.save(map_path)
print(f'Map saved: {map_path}')
from google.colab import files
files.download(map_path)

from google.colab import files
for fname in ['correlation_matrix.png','hypertension_bar_chart.png','scatter_anaemia_vs_obesity.png']:
    files.download(fname)
    print(f'Downloaded: {fname}')

"""---
## Final Summary Table

"""

summary = df[[
    'Obesity_Women','Obesity_Men','Gender_Obesity_Gap',
    'Anaemia_Children','Anaemia_Women',
    'HighBloodSugar_Women','HighBloodSugar_Men',
    'Hypertension_Women','Hypertension_Men'
]].sort_values('Gender_Obesity_Gap', ascending=False).round(2)

summary.style \
    .background_gradient(cmap='YlOrRd', subset=['Obesity_Women','Anaemia_Children']) \
    .background_gradient(cmap='Blues',  subset=['Hypertension_Men','Hypertension_Women']) \
    .format("{:.1f}%")